---
- name: otx events
  hosts: all
  sources:
    - name: Match all messages
      otx:
        count: "1"
  rules:
    - name: Send to playboox
      condition: event.otx is defined
      action:
        run_playbook:
          name: otx_ufw.yml
